# Dependencies
#markdown:         redcarpet
#highlighter:      rogue

# Permalinks
permalink:        pretty
gems: 		  [jekyll-paginate]

# Setup
title:            Data and Stuff 
tagline:          'My blog of class assignments and exploring data science'
description:      'My name is Dinesh Hemnani and I am a Business Analytics Graduate Student at Drexel University'
url:              https://dineshhmn.github.io
baseurl:          /

author:
  name:           'DINESH HEMNANI'
  url:            https://dineshhmn.github.io
  github:         https://github.com/dineshhmn

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/dineshhmn
